//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureADBearerAuth {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AzureADSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AzureADSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzureADBearerAuth.AzureADSettings", typeof(AzureADSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://contoso.onmicrosoft.com/TodoListService.
        /// </summary>
        public static string Audience {
            get {
                return ResourceManager.GetString("Audience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d3dev.onmicrosoft.com.
        /// </summary>
        public static string Tenant {
            get {
                return ResourceManager.GetString("Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b47cbfa7-58e2-4880-8aba-8e4c29db1f42.
        /// </summary>
        public static string TenantId {
            get {
                return ResourceManager.GetString("TenantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1e8a7e23-88d7-49fa-83e4-e767622b2288.
        /// </summary>
        public static string testclient_ClientId {
            get {
                return ResourceManager.GetString("testclient_ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8b064a41-8b59-41f6-b4ab-1c44ed077011.
        /// </summary>
        public static string TodoListDemo_ClientId {
            get {
                return ResourceManager.GetString("TodoListDemo_ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MfKvG2GFuRq0B6lno9yxdStJXShhU0GvkO2RkpYmn/Y=.
        /// </summary>
        public static string TodoListDemo_ClientSecret {
            get {
                return ResourceManager.GetString("TodoListDemo_ClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ahTGf9Xjkf7JpJjcXNCIMetqR/3A7HNu2y4xJockU9E=.
        /// </summary>
        public static string TodoListDemo_ClientSecret_2 {
            get {
                return ResourceManager.GetString("TodoListDemo_ClientSecret_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary01.
        /// </summary>
        public static string User1_Password {
            get {
                return ResourceManager.GetString("User1_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test01@d3dev.onmicrosoft.com.
        /// </summary>
        public static string User1_UserName {
            get {
                return ResourceManager.GetString("User1_UserName", resourceCulture);
            }
        }
    }
}
